/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_lazygamer1111_components_output_ESC */

#ifndef _Included_com_github_lazygamer1111_components_output_ESC
#define _Included_com_github_lazygamer1111_components_output_ESC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_lazygamer1111_components_output_ESC
 * Method:    init_SM
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_lazygamer1111_components_output_ESC_init_1SM
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_lazygamer1111_components_output_ESC
 * Method:    put
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_com_github_lazygamer1111_components_output_ESC_put
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     com_github_lazygamer1111_components_output_ESC
 * Method:    pop
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_github_lazygamer1111_components_output_ESC_pop
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
